PLAYER_LIGHT = "light"
PLAYER_DARK = "dark"
PLAYER_VALUES = (PLAYER_LIGHT, PLAYER_DARK)

GAME_STATUS_IN_PROGRESS = "IN_PROGRESS"
GAME_STATUS_FINISHED = "FINISHED"

DEFAULT_PLAYER_TIME_SECONDS = 300

API_STATUS_OK = "ok"
