# Generated by Django 6.0.4 on 2026-04-14 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.JSONField()),
                ('status', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('current_turn', models.CharField(default='LIGHT', max_length=10)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('player_time_remaining', models.IntegerField(default=300)),
                ('last_move_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pos', models.JSONField()),
                ('to_pos', models.JSONField()),
                ('is_jump', models.BooleanField(default=False)),
                ('captured_pos', models.JSONField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('board_before', models.JSONField()),
                ('time_spent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='checkers.game')),
            ],
        ),
    ]
