# Generated by Django 6.0.4 on 2026-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0002_normalize_player_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_move_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_time_remaining',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='moveentry',
            name='time_spent',
            field=models.PositiveIntegerField(),
        ),
    ]
