# Generated by Django 6.0.4 on 2026-04-18

from django.db import migrations, models


def copy_shared_timer_to_player_timers(apps, schema_editor):
    Game = apps.get_model("checkers", "Game")
    for game in Game.objects.all().only("id", "player_time_remaining"):
        remaining = game.player_time_remaining
        game.light_time_remaining = remaining
        game.dark_time_remaining = remaining
        game.save(update_fields=["light_time_remaining", "dark_time_remaining"])


def restore_shared_timer_from_player_timers(apps, schema_editor):
    Game = apps.get_model("checkers", "Game")
    for game in Game.objects.all().only("id", "current_turn", "light_time_remaining", "dark_time_remaining"):
        if game.current_turn == "dark":
            game.player_time_remaining = game.dark_time_remaining
        else:
            game.player_time_remaining = game.light_time_remaining
        game.save(update_fields=["player_time_remaining"])


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0003_alter_game_last_move_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="dark_time_remaining",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="game",
            name="light_time_remaining",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.RunPython(copy_shared_timer_to_player_timers, restore_shared_timer_from_player_timers),
        migrations.RemoveField(
            model_name="game",
            name="player_time_remaining",
        ),
    ]
