# Generated by Django 6.0.4 on 2026-04-18 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0004_split_player_timers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_move_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
