# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models


PLAYER_LIGHT_INT = 1
PLAYER_DARK_INT = 2
PLAYER_LIGHT_STR = "light"
PLAYER_DARK_STR = "dark"


def _to_int_player(value):
    if value in (PLAYER_LIGHT_INT, "1", PLAYER_LIGHT_STR, "LIGHT"):
        return PLAYER_LIGHT_INT
    if value in (PLAYER_DARK_INT, "2", PLAYER_DARK_STR, "DARK"):
        return PLAYER_DARK_INT
    return value


def _to_str_player(value):
    if value in (PLAYER_LIGHT_INT, "1", PLAYER_LIGHT_STR, "LIGHT"):
        return PLAYER_LIGHT_STR
    if value in (PLAYER_DARK_INT, "2", PLAYER_DARK_STR, "DARK"):
        return PLAYER_DARK_STR
    return value


def _convert_board_players(board_json, converter):
    if not isinstance(board_json, list):
        return board_json, False

    changed = False
    converted_board = []

    for row in board_json:
        if not isinstance(row, list):
            converted_board.append(row)
            continue

        converted_row = []
        for cell in row:
            converted_cell = cell
            if isinstance(cell, dict) and "player" in cell:
                original_player = cell.get("player")
                next_player = converter(original_player)
                if next_player != original_player:
                    converted_cell = dict(cell)
                    converted_cell["player"] = next_player
                    changed = True
            converted_row.append(converted_cell)
        converted_board.append(converted_row)

    if not changed:
        return board_json, False
    return converted_board, True


def convert_player_values_forward(apps, schema_editor):
    Game = apps.get_model("checkers", "Game")
    MoveEntry = apps.get_model("checkers", "MoveEntry")

    for game in Game.objects.all().only("id", "current_turn", "winner", "board"):
        update_fields = []

        next_current_turn = _to_int_player(game.current_turn)
        if next_current_turn != game.current_turn:
            game.current_turn = next_current_turn
            update_fields.append("current_turn")

        if game.winner is None:
            next_winner = None
        else:
            next_winner = _to_int_player(game.winner)
        if next_winner != game.winner:
            game.winner = next_winner
            update_fields.append("winner")

        next_board, board_changed = _convert_board_players(game.board, _to_int_player)
        if board_changed:
            game.board = next_board
            update_fields.append("board")

        if update_fields:
            game.save(update_fields=update_fields)

    for move in MoveEntry.objects.all().only("id", "board_before"):
        next_board_before, board_changed = _convert_board_players(move.board_before, _to_int_player)
        if board_changed:
            move.board_before = next_board_before
            move.save(update_fields=["board_before"])


def convert_player_values_reverse(apps, schema_editor):
    Game = apps.get_model("checkers", "Game")
    MoveEntry = apps.get_model("checkers", "MoveEntry")

    for game in Game.objects.all().only("id", "current_turn", "winner", "board"):
        update_fields = []

        next_current_turn = _to_str_player(game.current_turn)
        if next_current_turn != game.current_turn:
            game.current_turn = next_current_turn
            update_fields.append("current_turn")

        if game.winner is None:
            next_winner = None
        else:
            next_winner = _to_str_player(game.winner)
        if next_winner != game.winner:
            game.winner = next_winner
            update_fields.append("winner")

        next_board, board_changed = _convert_board_players(game.board, _to_str_player)
        if board_changed:
            game.board = next_board
            update_fields.append("board")

        if update_fields:
            game.save(update_fields=update_fields)

    for move in MoveEntry.objects.all().only("id", "board_before"):
        next_board_before, board_changed = _convert_board_players(move.board_before, _to_str_player)
        if board_changed:
            move.board_before = next_board_before
            move.save(update_fields=["board_before"])


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0005_alter_game_last_move_at"),
    ]

    operations = [
        migrations.RunPython(convert_player_values_forward, convert_player_values_reverse),
        migrations.AlterField(
            model_name="game",
            name="current_turn",
            field=models.PositiveSmallIntegerField(choices=[(1, "light"), (2, "dark")], default=1),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "light"), (2, "dark")],
                null=True,
            ),
        ),
    ]
